version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            NODE_ENV: development
            PORT: 3030
        ports:
            - "13030:3030"